apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "temporal.fullname" . }}-config
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
data:
  config.toml: |
    [app]
    address = "{{ .Values.config.app.address }}"

    [db]
    host = "{{ .Values.database.host }}"
    port = {{ .Values.database.port }}
    user = "{{ .Values.database.user }}"
    database = "{{ .Values.database.name }}"
    ssl_mode = "{{ .Values.database.sslmode }}"
