{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal.fullname" . }}-db
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | default "changeme" | quote }}
{{- if and .Values.ui.enabled .Values.ui.oidc.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal.fullname" . }}-ui-oidc
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.ui.oidc.clientSecret | quote }}
{{- end }}
{{- end }}
