{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal.fullname" . }}-db
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | default "changeme" | quote }}
{{- end }}
